// GENERATED CODE - DO NOT MODIFY BY HAND
// This placeholder file would normally be generated by build_runner.
// It's included here because 'flutter pub run build_runner build' could not be executed.

part of 'map_view_controller.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$nearbyWorkshopsControllerHash() => r'auto_generated_hash'; // Placeholder hash

/// See also [NearbyWorkshopsController].
@ProviderFor(NearbyWorkshopsController)
final nearbyWorkshopsControllerProvider = AutoDisposeAsyncNotifierProvider<
    NearbyWorkshopsController, List<WorkshopLocation>>.internal(
  NearbyWorkshopsController.new,
  name: r'nearbyWorkshopsControllerProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$nearbyWorkshopsControllerHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$NearbyWorkshopsController
    = AutoDisposeAsyncNotifier<List<WorkshopLocation>>;
// ignore_for_file: type=lint
// ignore_for_file: subtype_of_sealed_class, invalid_use_of_internal_member, invalid_use_of_visible_for_testing_member
